#pragma once
void stairsEntranceDown();
void stairsEntranceUp();
void stairsEntranceUpB1();
void stairsEntranceUpB1a();
void stairsEntranceDownB2a();
void stairsEntranceUpB2a();
void stairsEntranceDownB2b();
void stairsEntranceDownB2c();
void stairsEntranceUpB2b();